# Generated by Django 4.0.6 on 2023-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='x_when_y_zero',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='y_when_x_zero',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
