# Generated by Django 4.0.6 on 2023-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_problems_x_when_y_zero_problems_y_when_x_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='x_intersection',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='y_intersection',
            field=models.FloatField(null=True),
        ),
    ]
