# Generated by Django 4.0.6 on 2023-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_problems_x_intersection_problems_y_intersection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='line1_equation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='line2_equation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
