# Generated by Django 4.0.6 on 2023-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_problems_line1_equation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='base',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='x_intersection',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='y_intersection',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
