# Generated by Django 4.0.6 on 2023-08-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_problems_area_alter_problems_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='area_in',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='x_intercept',
        ),
    ]
