# Generated by Django 4.0.6 on 2023-08-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_problems_solution_x_alter_problems_solution_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='a_fl',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='b_fl',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='c_fl',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
