# Generated by Django 4.0.6 on 2023-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_problems_a_fl_alter_problems_b_fl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='a_fl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='b_fl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='c_fl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
