# Generated by Django 4.0.6 on 2023-08-23 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_alter_problems_a_fl_alter_problems_b_fl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equation',
        ),
        migrations.AddField(
            model_name='problems',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='my_equa',
        ),
    ]
