# Generated by Django 4.0.6 on 2023-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_solvedexercise_context_solvedexercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedexercise',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
