# Generated by Django 4.0.6 on 2023-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_studentresponse_delete_solvedexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='solved_by',
        ),
        migrations.AddField(
            model_name='problems',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
    ]
