# Generated by Django 4.0.6 on 2023-09-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_problems_solved_by_problems_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
