# Generated by Django 4.0.6 on 2023-09-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_problems_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='password_reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
