# Generated by Django 4.0.6 on 2023-09-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_customuser_invalidated_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invalidated_tokens',
        ),
    ]
